"""Render docs/EXPERIMENT_LEADERBOARD.md from data/cache/results.jsonl (the source of truth)."""
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import pandas as pd

from src import data, experiment as E

DOC = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), 'docs',
                   'EXPERIMENT_LEADERBOARD.md')

HEADER = """# Sprint 2 — Experiment Leaderboard

Auto-generated by `scripts/make_leaderboard.py` from `data/cache/results.jsonl` (every run
appends there via `src/experiment.log`). Do not edit the table by hand.

All EMR figures: one fixed **GroupShuffleSplit(groups = exact CRM configuration, 20% val,
seed 42)** split of train.csv (151,057 train / 36,385 val rows) unless the params say
`split_seed`, scored against **consensus targets** (modal full BIL configuration per CRM
configuration). 0% of validation rows have a CRM configuration seen in the training fold,
matching the real test set (6 of 97,100 test rows, 0.006%, have a config seen in train). Pipelines: `raw` = all 745 CRM columns; `s10` /
`s11` = Sprint 1 Section 10 / Section 11 feature sets; `+consensus` = trained on unique
configurations with consensus labels.

"""


def main():
    rows = [json.loads(l) for l in open(E.RESULTS)]
    best = max((r for r in rows if not r['exp_id'].startswith('EXT')), key=lambda r: r['emr'])
    out = [HEADER,
           f"**Current Champion:** {best['exp_id']} — {best['family']} ({best['pipeline']}) — "
           f"**{best['emr']:.2%} val EMR**, Hamming loss {best['hamming_loss']:.6f}.\n\n",
           '| Exp ID | Data Pipeline (Sec 10 vs 11) | Model Family | Key Hyperparameters / Features '
           '| Val EMR (%) | Val Hamming Loss | Train Time (s) | Status / Notes |\n',
           '|---|---|---|---|---|---|---|---|\n']
    for r in rows:
        params = ', '.join(f'{k}={v}' for k, v in r['params'].items()) or '—'
        mark = ' **(champion)**' if r is best else ''
        out.append(f"| {r['exp_id']} | {r['pipeline']} | {r['family']} | {params} | "
                   f"{r['emr'] * 100:.2f} | {r['hamming_loss']:.6f} | {r['train_time_s']} | "
                   f"{r['notes']}{mark} |\n")
    with open(DOC, 'w', encoding='utf-8') as f:
        f.writelines(out)
    flat = pd.DataFrame([{**{k: v for k, v in r.items() if k != 'params'},
                          'params': json.dumps(r['params'])} for r in rows])
    flat.to_csv(os.path.join(data.DERIVED_DIR, 'sprint2_experiment_results.csv'), index=False)
    print(f'{len(rows)} experiments -> {DOC}; champion {best["exp_id"]} {best["emr"]:.4%}')


if __name__ == '__main__':
    main()
